# Generated by Django 4.0.5 on 2022-06-28 22:10

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True)),
                ('title', models.CharField(blank=True, max_length=1023)),
                ('text', models.TextField(blank=True, max_length=65535)),
                ('file', models.FileField(blank=True, max_length=255, upload_to='files/')),
                ('votes', models.IntegerField(default=1)),
                ('data', models.JSONField(blank=True, null=True)),
                ('src', models.URLField(blank=True, max_length=1023)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('next', models.OneToOneField(blank=True, help_text='The next card in this thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='core.card')),
                ('parent', models.ForeignKey(blank=True, help_text='If null, this is a top level card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.card')),
                ('root', models.ForeignKey(blank=True, help_text='If null, this is a top level card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='core.card')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.card')),
            ],
        ),
    ]
