# Generated by Django 4.0.5 on 2022-07-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True, help_text='If specified, allow viewing this card at this url for the above specified site. A url is a series of only lowercase letters, numbers, and slashes and ends with a slash.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, help_text='A description of this card. If this card is used as the root card of a webpage, it will be used as the meta description text.', max_length=8191),
        ),
    ]
