# Generated by Django 4.0.5 on 2022-07-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_card_slug_card_url_alter_card_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(blank=True, help_text='If specified, allow viewing this card at this url for the above specified site. A url is a series of only lowercase letters, numbers, and slashes and ends with a slash.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='googledocbridge',
            name='google_doc_url',
            field=models.CharField(max_length=1023),
        ),
    ]
