# Generated by Django 4.0.5 on 2022-07-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_googledoc_delete_googledocbridge_alter_card_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
