# Generated by Django 4.0.5 on 2022-07-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNGImageViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
