# Generated by Django 4.0.5 on 2022-07-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mp4imageviewer_title_pngimageviewer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_32x32',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
