# Generated by Django 4.0.4 on 2022-05-24 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('assets', 'Assets'), ('liability', 'Liability'), ('equity', "Owner's Equity")], max_length=40)),
                ('description', models.TextField(blank=True, max_length=8191)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.moneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BTC', 'BTC'), ('ETH', 'ETH')], max_length=5)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('inflowing_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='core.moneyaccount')),
                ('outflowing_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='core.moneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=1023)),
                ('slug', models.SlugField(max_length=1023)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='products/%Y/%m/')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='cards/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProductUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlocks', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='core.moneyflow')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.product')),
            ],
        ),
    ]
